export const LINKEDIN_POST_GET_REQUEST = "LINKEDIN_POST_GET_REQUEST"
export const LINKEDIN_POST_GET_SUCCESS = "LINKEDIN_POST_GET_SUCCESS"
export const LINKEDIN_POST_GET_FAILURE = "LINKEDIN_POST_GET_FAILURE"

export const UPLOADING_POST_REQUEST = "UPLOADING_POST_REQUEST"
export const UPLOADING_POST_SUCCESS = "UPLOADING_POST_SUCCESS"
export const UPLOADING_POST_FAILURE = "UPLOADING_POST_FAILURE"

export const MAKE_LIKE_REQUEST = "MAKE_LIKE_REQUEST"
export const MAKE_LIKE_SUCCESS = "MAKE_LIKE_SUCCESS"
export const MAKE_LIKE_FAILURE = "MAKE_LIKE_FAILURE"

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_SUCCESS="POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAILURE ="POST_COMMENT_FAILURE"